name: "Telegram Message Notification"
author: "AliuQ"
description: "Send message to Telegram"
inputs:
  bot_token:
    description: "Telegram Bot Token"
    required: true
  chat_id:
    description: "Telegram Chat ID"
    required: true
  message:
    description: "Message to send"
    required: true
    default: ""
  reply_to_message_id:
    description: "Topic ID"
    required: false
    default: ""
  buttons:
    description: "JSON string of button configuration"
    required: false
    default: ""
  disable_link_preview:
    description: "Disable link preview"
    required: false
    default: "true"

outputs:
  message_id:
    description: "ID of the sent message"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "message-square"
  color: "blue"
