import type { Bot, InputFile } from 'grammy';
import type {
  InlineKeyboardMarkup,
  InputMediaAudio,
  InputMediaDocument,
  InputMediaPhoto,
  InputMediaVideo,
} from 'grammy/types';

export type AttachmentType = 'photo' | 'video' | 'audio' | 'animation' | 'document';

/**
 * Shared Telegram attachment option surface used by all supported senders.
 */
export interface AttachmentSendOptions {
  /** Optional caption sent together with the attachment. */
  caption?: string;
  /** Telegram parse mode used for captions generated by this project. */
  parse_mode?: 'MarkdownV2';
  /** Inline keyboard attached to the outgoing message. */
  reply_markup?: InlineKeyboardMarkup;
  /** Topic/thread target for forum-style chats. */
  message_thread_id?: number;
  /** Reply target for chaining messages together. */
  reply_parameters?: { message_id: number };
  /** Keep uploads in document mode instead of Telegram auto-detecting media. */
  disable_content_type_detection?: boolean;
  /** Request Telegram's streamable video presentation for single videos. */
  supports_streaming?: boolean;
}

/**
 * Common sender signature used to dispatch supported attachment requests.
 */
export type AttachmentSender = (
  bot: Bot,
  chatId: string,
  source: InputFile | string,
  options: AttachmentSendOptions,
) => Promise<{ message_id: number }>;

/**
 * Raw values read from the GitHub Actions input boundary.
 *
 * All action inputs arrive as strings at this stage, before validation and
 * normalization happen in the parser.
 */
export interface RawActionInputs {
  /** Optional scenario identifier injected by local tooling. */
  scenarioId?: string;
  /** Bot token read from the environment boundary. */
  botToken: string;
  /** Raw chat identifier from the environment boundary. */
  chatId: string;
  /** Inline message text. */
  message: string;
  /** Repository-local path whose UTF-8 contents become the message body. */
  messageFile: string;
  /** Remote HTTP(S) URL whose body becomes the message text. */
  messageUrl: string;
  /** Raw inline keyboard JSON. */
  buttons: string;
  /** Raw topic/thread id from the environment boundary. */
  topicId: string;
  /** Raw reply target message id from the environment boundary. */
  replyToMessageId: string;
  /** Raw toggle for link preview behavior. */
  disableLinkPreview: string;
  /** Single attachment source string. */
  attachment: string;
  /** Multi-attachment JSON payload. */
  attachments: string;
  /** Raw single-attachment type. */
  attachmentType: string;
  /** Optional filename override for local uploads. */
  attachmentFilename: string;
  /** Raw toggle for Telegram video streaming mode. */
  supportsStreaming: string;
  /** Raw failure behavior toggle for the action step. */
  exitOnFail: string;
}

/**
 * Resolved attachment payload after the source string has been interpreted.
 */
export interface ResolvedAttachmentSource {
  /** Telegram-ready source value: local InputFile, URL, or file_id. */
  value: InputFile | string;
  /** Whether the source came from a workspace-local file path. */
  isLocalFile: boolean;
}

/**
 * Normalized action request after parsing, validation, and type coercion.
 */
export interface ParsedActionInputs {
  /** Optional scenario identifier for local runs and debug output. */
  scenarioId?: string;
  /** Bot token after validation. */
  botToken: string;
  /** Normalized chat id used for Telegram API calls. */
  chatId: string;
  /** Resolved message body, if present. */
  message?: string;
  /** Final link preview toggle. */
  disableLinkPreview: boolean;
  /** Parsed topic/thread id, if present. */
  topicId?: number;
  /** Parsed reply target message id, if present. */
  replyMessageId?: number;
  /** Parsed inline keyboard payload. */
  replyMarkup?: InlineKeyboardMarkup;
  /** Parsed single-attachment type, if present. */
  attachmentType?: AttachmentType;
  /** Parsed single-attachment source, if present. */
  attachmentSource?: ResolvedAttachmentSource;
  /** Parsed multi-attachment payload, if present. */
  attachmentItems?: ParsedAttachmentItem[];
  /** Whether single-video sends should request Telegram streaming mode. */
  supportsStreaming: boolean;
  /** Whether action failures should fail the workflow step. */
  exitOnFail: boolean;
}

/**
 * Raw attachment item shape accepted by the `attachments` JSON input.
 */
export interface RawAttachmentItemInput {
  /** Telegram attachment kind for this item. */
  type: AttachmentType;
  /** Local path, URL, or Telegram file_id. */
  source: string;
  /** Optional upload filename override for local files. */
  filename?: string;
  /** Optional per-item caption. */
  caption?: string;
  /** Per-item video streaming flag used by `attachments`. */
  supports_streaming?: boolean;
}

/**
 * Parsed attachment item ready for single-send or media-group transport.
 */
export interface ParsedAttachmentItem {
  /** Telegram attachment kind for this item. */
  type: AttachmentType;
  /** Resolved attachment source. */
  source: ResolvedAttachmentSource;
  /** Optional upload filename override for local files. */
  filename?: string;
  /** Optional per-item caption after parsing. */
  caption?: string;
  /** Parsed per-item video streaming flag. */
  supportsStreaming?: boolean;
}

export type TelegramMediaGroupItem =
  | InputMediaAudio
  | InputMediaDocument
  | InputMediaPhoto
  | InputMediaVideo;

/**
 * Raw scenario input shape used by local tooling and workflow helpers.
 */
export interface ScenarioInputs {
  /** Inline message text used by the scenario. */
  message: string;
  /** Scenario-local message file input. */
  message_file: string;
  /** Scenario-local message URL input. */
  message_url: string;
  /** Scenario-local link preview toggle. */
  disable_link_preview: string;
  /** Scenario-local button JSON. */
  buttons: string;
  /** Scenario-local single attachment source. */
  attachment: string;
  /** Scenario-local multi-attachment payload. */
  attachments: string;
  /** Scenario-local single attachment type. */
  attachment_type: string;
  /** Scenario-local attachment filename override. */
  attachment_filename: string;
  /** Scenario-local single-video streaming toggle. */
  supports_streaming: string;
  /** Scenario-local failure behavior toggle. */
  exit_on_fail: string;
}

/**
 * Single test scenario definition.
 */
export interface ScenarioDefinition {
  /** Stable scenario id used by local tooling and CI selection. */
  id: string;
  /** Human-readable summary shown in prompts and docs. */
  description: string;
  /** Whether the scenario is expected to fail during validation or sending. */
  expect_failure: boolean;
  /** Whether this scenario should be included when act runs the full "all" workflow selection. */
  includeInActRunAll?: boolean;
  /** Raw action-like inputs for the scenario. */
  inputs: ScenarioInputs;
}

/**
 * Concrete scenario selection after parsing the workflow or local-runner input.
 */
export interface ScenarioSelection {
  /** Whether the full scenario catalog was selected. */
  runAll: boolean;
  /** Ordered list of selected scenario ids. */
  scenarioIds: string[];
  /** Resolved scenario objects in execution order. */
  selectedScenarios: ScenarioDefinition[];
}

/**
 * Supported execution modes for the local runner.
 */
export type TestMode = 'source' | 'act' | 'validate';

/**
 * Raw CLI options before interactive prompts fill in missing selections.
 */
export interface CliOptions {
  /** Explicit runner mode from the CLI, if provided. */
  mode?: TestMode;
  /** Whether `--all` was supplied. */
  runAll: boolean;
  /** Whether the runner should reuse the last stored command. */
  rerunLast: boolean;
  /** Scenario ids passed on the command line. */
  scenarioIds: string[];
}

/**
 * Fully resolved runner selection after CLI parsing and prompt handling.
 */
export interface TestSelection {
  /** Final runner mode after CLI parsing and prompt resolution. */
  mode: TestMode;
  /** Whether the full catalog should run. */
  runAll: boolean;
  /** Scenario ids selected for this run. */
  scenarioIds: string[];
}

/**
 * One persisted test-run history record.
 */
export interface TestHistoryEntry extends TestSelection {
  /** Copy-pasteable command for rerunning the selection. */
  command: string;
  /** ISO timestamp recorded when the run was created. */
  createdAt: string;
  /** Saved log file path for the run, if one was written. */
  logFile?: string;
  /** Elapsed time in milliseconds, when available. */
  durationMs?: number;
  /** Human-readable duration shown in the runner UI. */
  durationText?: string;
}

/**
 * History state saved by the interactive runner.
 */
export interface TestHistoryState {
  /** Most recent run, used for quick reruns. */
  lastRun?: TestHistoryEntry;
  /** Bounded history of recent runs. */
  runs: TestHistoryEntry[];
}

/**
 * Convenience alias for Telegram's nested inline-keyboard structure.
 */
export type InlineKeyboardMatrix = InlineKeyboardMarkup['inline_keyboard'];

/**
 * Data shown in local request previews and failure diagnostics.
 */
export interface ActRequestSummaryOptions {
  /** Optional scenario id shown in debug output. */
  scenarioId?: string;
  /** Telegram method summary for the request. */
  method: string;
  /** Target chat id, masked before display. */
  chatId: string;
  /** Message text used for size summaries. */
  message?: string;
  /** Final link preview toggle for the request. */
  disableLinkPreview: boolean;
  /** Topic/thread target, if present. */
  topicId?: number;
  /** Reply target, if present. */
  replyMessageId?: number;
  /** Parsed inline keyboard, if present. */
  replyMarkup?: InlineKeyboardMarkup;
  /** Single-attachment type used by the request, if any. */
  attachmentType?: AttachmentType;
  /** Single-attachment source summary, if any. */
  attachmentSource?: ResolvedAttachmentSource;
}
